# Конфигурация PrimPlugin

# Настройки базы данных (MySQL)
database:
  # Префикс таблиц плагина в базе данных (строка)
  # По умолчанию: "prim_"
  prefix: "prim_"

  # Настройки подключения к базе данных
  connection:
    # Адрес сервера MySQL (строка)
    # По умолчанию: "127.0.0.1"
    host: "127.0.0.1"

    # Порт сервера MySQL (положительное число)
    # Порт MySQL по умолчанию: 3306
    # По умолчанию: 3306
    port: 3306

    # База данных, в которой плагин будет хранить свои данные (строка)
    # По умолчанию: "minecraft"
    database: "minecraft"

  # Данные для авторизации в базе данных
  authorization:
    # Имя пользователя базы данных (строка)
    # По умолчанию: null
    username: "admin"

    # Пароль пользователя базы данных (строка)
    # По умолчанию: null
    password: "qwerty12345"