name: "PrimPlugin"
description: "${project.description}"
version: "${project.version}"
authors: [stngularity]
api-version: 1.19
main: ru.primland.plugin.PrimPlugin

permissions:
  primplugin.*:
    description: "Все права плагина PrimPlugin"
    default: op
    children:
      primplugin.commands.*: true
      primplugin.pickup_custom_items: true

  primplugin.commands.*:
    description: "Доступ ко всем командам PrimPlugin (НЕ ДАВАЙТЕ ЭТО ОБЫЧНЫМ ИГРОКАМ)"
    children:
      primplugin.commands.primary: true
      primplugin.commands.reload: true
      primplugin.commands.status: true
      primplugin.commands.rep.set: true
      primplugin.commands.cards.give_box: true
      primplugin.commands.cards.give_card: true
      primplugin.commands.heads.give: true
      primplugin.commands.whitelist.add: true
      primplugin.commands.whitelist.remove: true
      primplugin.commands.whitelist.list: true

  primplugin.commands.primary:
    description: "Доступ к основной (!) команде PrimPlugin"

  primplugin.commands.reload:
    description: "Доступ к команде /prim reload"

  primplugin.commands.status:
    description: "Доступ к команде /prim status"

  primplugin.commands.rep.set:
    description: "Доступ к команде /rep set {игрок} {репутация}"

  primplugin.commands.cards.primary:
    description: "Доступ к команде /cards"

  primplugin.commands.cards.give_box:
    description: "Доступ к команде /cards give-box [игрок] [количество]"
    children:
      primplugin.commands.cards.primary: true

  primplugin.commands.cards.give_card:
    description: "Доступ к команде /cards give-card {редкость} {ID карточки} [игрок]"
    children:
      primplugin.commands.cards.primary: true

  primplugin.commands.heads.primary:
    description: "Доступ к команде /heads"

  primplugin.commands.heads.give:
    description: "Доступ к команде /heads give {игрок} [получатель]"
    children:
      primplugin.commands.heads.primary: true

  primplugin.commands.whitelist.add:
    description: "Доступ к команде /plwl add {игрок} (Добавить игрока в белый список)"

  primplugin.commands.whitelist.remove:
    description: "Доступ к команде /plwl remove {игрок} (Удалить игрока из белого списка)"

  primplugin.commands.whitelist.list:
    description: "Доступ к команде /plwl list (Посмотреть список людей в белом списке)"

  primplugin.pickup_custom_items:
    description: "Возможность поднимать кастомные вещи"