name: "PrimPlugin"
description: "${project.description}"
version: "${project.version}"
authors: [stngularity]
api-version: 1.19
main: ru.primland.plugin.PrimPlugin

permissions:
  primplugin.*:
    description: "Все права плагина PrimPlugin"
    default: op
    children:
      primplugin.commands.*: true
      primplugin.pickupCustomWeapons: true

  primplugin.commands.*:
    description: "Доступ ко всем командам PrimPlugin (НЕ ДАВАЙТЕ ЭТО ОБЫЧНЫМ ИГРОКАМ)"
    children:
      primplugin.commands.primary: true
      primplugin.commands.reload: true
      primplugin.commands.rep.set: true
      primplugin.commands.cards.giveBox: true
      primplugin.commands.cards.get: true
      primplugin.commands.headDrop.getHead: true
      primplugin.commands.whitelist.add: true
      primplugin.commands.whitelist.remove: true
      primplugin.commands.whitelist.list: true

  primplugin.commands.primary:
    description: "Доступ к основной (!) команде PrimPlugin"

  primplugin.commands.reload:
    description: "Доступ к команде /prim reload (Перезагрузить плагин)"

  primplugin.commands.rep.set:
    description: "Доступ к команде /rep set {игрок} {репутация} (Установить репутацию указанному игроку)"

  primplugin.commands.cards.giveBox:
    description: "Доступ к команде /prim cards give-box {игрок} [количество] (Выдать ящики с карточками)"

  primplugin.commands.cards.get:
    description: "Доступ к команде /prim cards get {редкость} {ID карточки} (Получить карточку)"

  primplugin.commands.headDrop.getHead:
    description: "Доступ к команде /prim heads get {игрок} (Получить голову указанного игрока)"

  primplugin.commands.whitelist.add:
    description: "Доступ к команде /plwl add {игрок} (Добавить игрока в белый список)"

  primplugin.commands.whitelist.remove:
    description: "Доступ к команде /plwl remove {игрок} (Удалить игрока из белого списка)"

  primplugin.commands.whitelist.list:
    description: "Доступ к команде /plwl list (Посмотреть список людей в белом списке)"

  primplugin.pickupCustomWeapons:
    description: "Возможность поднимать кастомные оружия"