name: "Сборка проекта"

on:
  push:
    tags: ["v*.*.*"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Получаем исходники
        uses: actions/checkout@v3
        
      - name: Устанавливаем JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Компилируем в JAR
        run: mvn package

      - name: Получаем версию
        run: |
          python3 -c "print('VERSION='+__import__('re').findall(r'<version>([^<]+)</version>',open('pom.xml','r',encoding='utf8').read())[0])" >> $GITHUB_ENV

      - name: Загружаем в артефакт
        uses: actions/upload-artifact@v3
        with:
          path: "${{ github.workspace }}/target/*.jar"
          name: "primplugin-v${{ env.VERSION }}"
          if-no-files-found: error
